name: Reusable gradle workflow to build and publish a docker image to GHCR

# WIP - We need to make it work with private registries

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version to use"
        type: string
        required: false
        default: "21"
      java-distribution:
        description: "Java distribution to use"
        type: string
        required: false
        default: "temurin"
      build-and-test:
        description: "Build and test at the same time"
        type: boolean
        required: false
        default: false
      disable-unit-test:
        description: "Disable unit testing job"
        type: string
        required: false
        default: "false"
      disable-integration-test:
        description: "Disable integration testing job"
        type: string
        required: false
        default: "false"
      disable-merge-test-reports:
        description: "Disable merging the test reports"
        type: string
        required: false
        default: "true" # https://github.com/kageiit/gradle-jacobo-plugin cobertura report also has this issue: https://github.com/python/mypy/issues/17689, disabling for now
      gh-advanced-security:
        description: "Enable if you have GitHub Advanced Security"
        type: boolean
        required: false
        default: false
      code-quality-info-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 10
      code-quality-minor-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 5
      code-quality-major-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 1
      code-quality-critical-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 0
      code-quality-blocker-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: phorus-group/gradle-build-action@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          build-and-test: ${{ inputs.build-and-test }}

  unit-test:
    name: Unit tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ inputs.disable-unit-test != 'true' }}
        uses: actions/checkout@v4

      - name: Run unit-tests
        if: ${{ inputs.disable-unit-test != 'true' }}
        uses: phorus-group/gradle-test-action@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          gradle-version: 8.5
          commands: check unitTest -x test
          artifact-suffix: unit

  integration-test:
    name: Integration tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ inputs.disable-integration-test != 'true' }}
        uses: actions/checkout@v4

      - name: Run integration-tests
        if: ${{ inputs.disable-integration-test != 'true' }}
        uses: phorus-group/gradle-test-action@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          gradle-version: 8.5
          commands: integrationTest
          artifact-suffix: integration

  merge-test-reports:
    name: Merge test reports
    if: ${{ inputs.disable-merge-test-reports != 'true' }}
    needs: [unit-test,integration-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ inputs.disable-integration-test != 'true' && inputs.disable-unit-test != 'true' }}
        uses: actions/checkout@v4

      - name: Merge test reports
        if: ${{ inputs.disable-integration-test != 'true' && inputs.disable-unit-test != 'true' }}
        uses: phorus-group/gradle-merge-reports-action@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          gradle-version: 8.5
          command: jacocoMergeReports
          test-artifact-1: gradle-tests-unit
          test-artifact-2: gradle-tests-integration

  code-quality:
    name: Code quality check
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code quality
        uses: phorus-group/code-quality-action@main
        with:
          info-threshold: ${{ inputs.code-quality-info-threshold }}
          minor-threshold: ${{ inputs.code-quality-minor-threshold }}
          major-threshold: ${{ inputs.code-quality-major-threshold }}
          critical-threshold: ${{ inputs.code-quality-critical-threshold }}
          blocker-threshold: ${{ inputs.code-quality-blocker-threshold }}

  vulnerability-analysis:
    name: Vulnerability analysis
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: gradle-build

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: "Generate gradle lockfile"
        run: |
          echo "allprojects { dependencyLocking { lockAllConfigurations() } }" >> ~/.gradle/init.gradle
          ./gradlew dependencies --write-locks

      - name: Analyse project for vulnerabilities
        uses: phorus-group/vulnerability-analysis-action@main
        with:
          skip-dirs: .git
          upload-sarif: ${{ inputs.gh-advanced-security }}

  docker:
    name: Docker build and push
    needs: [unit-test,integration-test,code-quality,vulnerability-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: gradle-build

      - name: "Check build folder"
        run: |
          ls -la
          ls -la build
          ls -la build/libs

      - name: Build and push Docker image
        uses: phorus-group/docker-action@main
        with:
          dockerfile-path: "dockerfiles/Dockerfile.gradle"
          push: true

  enforce-all-checks:
    name: Enforce all checks
    needs: [docker]
    if: ${{ github.ref_name != github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Enforce all checks
        uses: poseidon/wait-for-status-checks@main
        with:
          token: ${{ github.token }}
          ignore_pattern: ".*Enforce all checks"
