name: Reusable workflow to build and publish a NextJS docker image to GHCR

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use"
        type: string
        required: false
        default: "22.2.0"
      registry-scope:
        description: "Scope to use with the private registry"
        type: string
        required: false
      private-registry:
        description: "Private NPM registry to use"
        type: string
        required: false
        default: "npm.pkg.github.com"
      auth-key:
        description: "Auth key to use inside ~/.npmrc"
        type: string
        required: false
        default: "authToken"
      auth-value:
        description: "Auth value to use inside ~/.npmrc. Defaults to github.token"
        type: string
        required: false
      disable-unit-test:
        description: "Disable unit testing job"
        type: string
        required: false
        default: "false"
      disable-integration-test:
        description: "Disable integration testing job"
        type: string
        required: false
        default: "false"
      gh-advanced-security:
        description: "Enable if you have GitHub Advanced Security"
        type: boolean
        required: false
        default: false
      code-quality-info-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 10
      code-quality-minor-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 5
      code-quality-major-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 1
      code-quality-critical-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 0
      code-quality-blocker-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Configure npm registry globally in ~/.npmrc
        if: ${{ inputs.registry-scope != '' }}
        env:
          AUTH_VALUE: ${{ inputs.auth-value || github.token }}
        run: |
          echo "${{ inputs.registry-scope }}:registry=https://${{ inputs.private-registry }}" >> ~/.npmrc
          echo "//${{ inputs.private-registry }}/:_${{ inputs.auth-key }}=$AUTH_VALUE" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          include-hidden-files: true
          retention-days: 2
          path: |
            .next/standalone
            .next/static
            ./public

  unit-test:
    name: Unit tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ inputs.disable-unit-test != 'true' }}
        uses: actions/checkout@v4

      - name: Configure npm registry globally in ~/.npmrc
        if: ${{ inputs.registry-scope != '' }}
        env:
          AUTH_VALUE: ${{ inputs.auth-value || github.token }}
        run: |
          echo "${{ inputs.registry-scope }}:registry=https://${{ inputs.private-registry }}" >> ~/.npmrc
          echo "//${{ inputs.registry }}/:_${{ inputs.auth-key }}=$AUTH_VALUE" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Run unit-tests
        if: ${{ inputs.disable-unit-test != 'true' }}
        uses: phorus-group/yarn-test-action@main
        with:
          command: test:unit

      - name: Run storybook tests
        if: ${{ inputs.disable-unit-test != 'true' }}
        uses: phorus-group/yarn-test-action@main
        with:
          command: test:storybook:ci

  integration-test:
    name: Integration tests

    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ inputs.disable-integration-test != 'true' }}
        uses: actions/checkout@v4

      - name: Configure npm registry globally in ~/.npmrc
        if: ${{ inputs.registry-scope != '' }}
        env:
          AUTH_VALUE: ${{ inputs.auth-value || github.token }}
        run: |
          echo "${{ inputs.registry-scope }}:registry=https://${{ inputs.private-registry }}" >> ~/.npmrc
          echo "//${{ inputs.registry }}/:_${{ inputs.auth-key }}=$AUTH_VALUE" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Run integration-tests
        if: ${{ inputs.disable-integration-test != 'true' }}
        uses: phorus-group/yarn-test-action@main
        with:
          command: test:integration

  code-quality:
    name: Code quality check
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code quality
        uses: phorus-group/code-quality-action@main
        with:
          info-threshold: ${{ inputs.code-quality-info-threshold }}
          minor-threshold: ${{ inputs.code-quality-minor-threshold }}
          major-threshold: ${{ inputs.code-quality-major-threshold }}
          critical-threshold: ${{ inputs.code-quality-critical-threshold }}
          blocker-threshold: ${{ inputs.code-quality-blocker-threshold }}

  vulnerability-analysis:
    name: Vulnerability analysis
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Analyse project for vulnerabilities
        uses: phorus-group/vulnerability-analysis-action@main
        with:
          skip-dirs: node_modules,.git
          upload-sarif: ${{ inputs.gh-advanced-security }}

  docker:
    name: Docker build and push
    needs: [unit-test,integration-test,code-quality,vulnerability-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build

      - name: Build and push Docker image
        uses: phorus-group/docker-action@main
        with:
          dockerfile-path: "dockerfiles/Dockerfile.nextjs"
          push: true

  enforce-all-checks:
    name: Enforce all checks
    needs: [docker]
    if: ${{ github.ref_name != github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Enforce all checks
        uses: poseidon/wait-for-status-checks@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore_pattern: ".*Enforce all checks"
