name: Reusable Chromatic workflow

on:
  workflow_call:
    inputs:
      registry-scope:
        description: "Scope to use with the private registry"
        type: string
        required: false
      private-registry:
        description: "Private NPM registry to use"
        type: string
        required: false
        default: "npm.pkg.github.com"
      auth-key:
        description: "Auth key to use inside ~/.npmrc"
        type: string
        required: false
        default: "authToken"
    secrets:
      token:
        required: true
      auth-value:
        description: "Auth value to use inside ~/.npmrc. Defaults to secrets.PACKAGES_READ" # Remember that the github.token only has access to the current repo packages
        required: false

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure npm registry globally in ~/.npmrc
        if: ${{ inputs.registry-scope != '' }}
        run: |
          echo "${{ inputs.registry-scope }}:registry=https://${{ inputs.private-registry }}" >> ~/.npmrc
          echo "//${{ inputs.private-registry }}/:_${{ inputs.auth-key }}=${{ secrets.auth-value || secrets.PACKAGES_READ }}" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          rm -rf yarn.lock

      - name: Install dependencies
        run: yarn install #--frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@v11.17.0
        with:
          projectToken: ${{ secrets.token || secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          externals: public/**
