name: Reusable library workflow to build and publish a yarn library

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use"
        type: string
        required: false
        default: "22.2.0"
      registry:
        description: "NPM registry to use"
        type: string
        required: false
        default: "https://npm.pkg.github.com"
      access:
        description: "Package access. public / private"
        type: string
        required: false
        default: "private"
      auth-key:
        description: "Auth key to use inside ~/.npmrc"
        type: string
        required: false
        default: "authToken"
      auth-value:
        description: "Auth value to use inside ~/.npmrc"
        type: string
        required: false
        default: ${{ github.token }}
      disable-unit-test:
        description: "Disable unit testing job"
        type: string
        required: false
        default: "false"
      disable-integration-test:
        description: "Disable integration testing job"
        type: string
        required: false
        default: "false"
      gh-advanced-security:
        description: "Enable if you have GitHub Advanced Security"
        type: boolean
        required: false
        default: false
      code-quality-info-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 10
      code-quality-minor-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 5
      code-quality-major-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 1
      code-quality-critical-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 0
      code-quality-blocker-threshold:
        description: "The number of findings of this severity allowed before the job returns a failure"
        type: number
        required: false
        default: 0

jobs:
  validate-version:
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.package.outputs.name }}
      package-scope: ${{ steps.package.outputs.scope }}
      package-version: ${{ steps.package.outputs.version }}
      published-version: ${{ steps.published.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract package data from package.json
        id: package
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
          
          if [[ $PACKAGE_NAME != @*/* ]]; then
            echo "Error: Package name must be scoped (e.g., @scope/package-name)."
            exit 1
          fi
          
          PACKAGE_SCOPE=$(echo $PACKAGE_NAME | cut -d'/' -f1)
          echo "scope=$PACKAGE_SCOPE" >> $GITHUB_OUTPUT

      - name: Get published version from GitHub Package Registry
        id: published
        run: |
          echo "//${{ inputs.registry }}/:_${{ inputs.auth-key }}=${{ inputs.auth-value }}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          PUBLISHED_VERSION=$(npm view ${{ steps.package.outputs.name }} version --registry=${{ inputs.registry }} || echo "0.0.0")
          echo "version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install semver package
        run: |
          rm -f package.json package-lock.json yarn.lock
          npm install semver

      - name: Validate version
        run: |
          export PUBLISHED_VERSION=${{ steps.published.outputs.version }}
          export PACKAGE_VERSION=${{ steps.package.outputs.version }}
          node -e ' 
            const semver = require("semver");
            const current = process.env.PUBLISHED_VERSION || "0.0.0";
            const next = process.env.PACKAGE_VERSION;
            if (!semver.valid(next)) {
              console.error(`Error: package version is not a valid SemVer version. Version: ${next}`);
              process.exit(1);
            }
            if (!semver.valid(current)) {
              console.error(`Error: published version is not a valid SemVer version. Version: ${current}`);
              process.exit(1);
            }
            if (!semver.gt(next, current)) {
              console.error(`Error: Version ${next} is not greater than published ${current}`);
              process.exit(1);
            }
          '

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib-build
          include-hidden-files: true
          retention-days: 2
          path: |
            ./package.json
            ./dist

  unit-test:
    name: Unit tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ inputs.disable-unit-test != 'true' }}
        uses: actions/checkout@v4

      - name: Run unit-tests
        if: ${{ inputs.disable-unit-test != 'true' }}
        uses: phorus-group/yarn-test-action@main
        with:
          command: test:unit

      - name: Run storybook tests
        if: ${{ inputs.disable-unit-test != 'true' }}
        uses: phorus-group/yarn-test-action@main
        with:
          command: test:storybook:ci

  integration-test:
    name: Integration tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ inputs.disable-integration-test != 'true' }}
        uses: actions/checkout@v4

      - name: Run integration-tests
        if: ${{ inputs.disable-integration-test != 'true' }}
        uses: phorus-group/yarn-test-action@main
        with:
          command: test:integration

  code-quality:
    name: Code quality check
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code quality
        uses: phorus-group/code-quality-action@main
        with:
          info-threshold: ${{ inputs.code-quality-info-threshold }}
          minor-threshold: ${{ inputs.code-quality-minor-threshold }}
          major-threshold: ${{ inputs.code-quality-major-threshold }}
          critical-threshold: ${{ inputs.code-quality-critical-threshold }}
          blocker-threshold: ${{ inputs.code-quality-blocker-threshold }}

  vulnerability-analysis:
    name: Vulnerability analysis
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Analyse project for vulnerabilities
        uses: phorus-group/vulnerability-analysis-action@main
        with:
          skip-dirs: node_modules,.git
          upload-sarif: ${{ inputs.gh-advanced-security }}

  publish:
    name: Publish library
    needs: [validate-version,unit-test,integration-test,code-quality,vulnerability-analysis]
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lib-build

      - name: Configure npm registry globally in ~/.npmrc
        run: |
          echo "${{ needs.validate-version.outputs.package-scope }}:registry=${{ inputs.registry }}" > ~/.npmrc
          echo "//${{ inputs.registry }}/:_${{ inputs.auth-key }}=${{ inputs.auth-value }}" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Publish package
        run: yarn publish --new-version $(jq -r .version package.json) --non-interactive --access ${{ inputs.access }}

  enforce-all-checks:
    name: Enforce all checks
    needs: [validate-version,unit-test,integration-test,code-quality,vulnerability-analysis]
    if: ${{ github.ref_name != github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Enforce all checks
        uses: poseidon/wait-for-status-checks@main
        with:
          token: ${{ github.token }}
          ignore_pattern: ".*Enforce all checks"
